Add Vpc resource
aws-controllers-k8s/ec2-controller pull request #1
Opened 2021-08-03 19:00 UTC by brycahta

* Adding create/delete VPC functionality with smoke tests
* Adding Makefile
* Adding metadata file

2021-08-03 19:26 UTC, RedbackThomson requested changes
Super clean. Seems fairly straightforward and I hope will be a good basis for a lot of the other resources. 

Biggest thing is just to remove the `DryRun` field from spec - add to list of ignored fields.

I've left some minor nits about code style, but nothing major from me otherwise.

2021-08-03 19:26 UTC, RedbackThomson commented on apis/v1alpha1/vpc.go
> +	DryRun *bool `json:"dryRun,omitempty"`
Please add to the ignored fields list

2021-08-03 19:26 UTC, RedbackThomson commented on pkg/resource/vpc/hooks.go
> +func isRequiredFieldsMissingFromInput(r *resource) bool {
For godoc, please use the name of the method as the first word in the doc. e.g.:
```
isRequiredFieldsMissingFromInput returns True if any required fields in the input shape are missing...
```

2021-08-03 19:26 UTC, RedbackThomson commented on pkg/resource/vpc/hooks.go
> +	return errors.New("unable to extract vpcId from Kubernetes resource")
super nit: Early return pattern

```suggestion
	if r.ko.Status.VPCID == nil {
		return errors.New("unable to extract VPCID from Kubernetes resource")
	}
	input.VpcIds = []*string{r.ko.Status.VPCID}
	return nil
```

2021-08-03 19:26 UTC, RedbackThomson commented on templates/hooks/vpc/sdk_read_many_post_build_request.go.tpl
> +	}
nit: Conditional can be shortened to a one-liner
```suggestion
	if err = addIdToListRequest(r, input); err != nil {
		return nil, ackerr.NotFound
	} 
```

2021-08-03 19:26 UTC, RedbackThomson commented on test/e2e/tests/test_vpc.py
> +        resource_name = "vpc-ack-test"
Please use the [`resources.random_suffix_name`](https://github.com/aws-controllers-k8s/test-infra/blob/main/src/acktest/resources.py#L54) method to autogenerate a name. Otherwise if multiple test runs are invoked in parallel they could collide.

2021-08-03 21:03 UTC, vijtrip2 commented
Looks solid beside incorporating Nick's comments.

2021-08-03 23:11 UTC, RedbackThomson commented on pkg/resource/vpc/hooks.go
> +func addIdToListRequest(r *resource, input *svcsdk.DescribeVpcsInput) error {
super nit: `Id` -> `ID`. We try to use the proper capitalisation in all the Go code except for when it's an external type.

2021-08-03 23:12 UTC, RedbackThomson approved these changes
Great! Will let someone else check it out, but looks solid to me.

2021-08-04 09:50 UTC, A-Hilaly commented
Neat :+1:
/ok-to-test

2021-08-04 10:38 UTC, A-Hilaly commented
holding until we add pre-submit jobs for ec2-controller (https://github.com/aws-controllers-k8s/test-infra/pull/82)
/hold

2021-08-04 13:13 UTC, jaypipes commented
/unhold

2021-08-04 13:43 UTC, jaypipes approved these changes
Nice work on this, @brycahta! Left some comments inline that are mostly to the ACK core team (/cc @vijtrip2 @RedbackThomson @A-Hilaly) for things we need to do to the code-generator to avoid the need for some of the custom code you've had to place in here.

2021-08-04 13:43 UTC, jaypipes commented on apis/v1alpha1/types.go
> +	DpdTimeoutAction     *string `json:"dpdTimeoutAction,omitempty"`
@brycahta "Dpd" here should be normalized to "DPD". If you'd like to submit a patch to the code-generator repo correcting this, @RedbackThomson or @A-Hilaly can walk you through the process (it's a relatively simple change to https://github.com/aws-controllers-k8s/code-generator/blob/main/pkg/names/names.go)

2021-08-04 13:43 UTC, jaypipes commented on apis/v1alpha1/types.go
> +	IoPerformance *string `json:"ioPerformance,omitempty"`
Likewise this should be normalized to "IOPerformance" (in a future PR to the code-generator, nothing to do for this PR)

2021-08-04 13:43 UTC, jaypipes commented on generator.yaml
> +    - CreateVpcInput.DryRun
:+1:

2021-08-04 13:43 UTC, jaypipes commented on pkg/resource/vpc/hooks.go
> +// fields in the input shape are missing meaning AWS resource is
Couple things...

1) Maybe it was a copy-pasta mistake, but this function isn't analyzing "the input shape". It's analyzing the CR (`r *resource`) to check if `Status.State` is nil.

2) This is actually what the code-generator's [`pkg/generate/code.CheckRequiredFieldsMissingFromShape` generator function](https://github.com/aws-controllers-k8s/code-generator/blob/843e3dd57998a61a0cd460de4da6ea1467a6f036/pkg/generate/code/check.go#L60-L93) should be used for. As you can see from that code, however, we don't yet implement it for ReadMany operations. We should get this done and you won't need a custom hook for this after that.

2021-08-04 13:43 UTC, jaypipes commented on pkg/resource/vpc/hooks.go
> +func addIDToListRequest(r *resource, input *svcsdk.DescribeVpcsInput) error {
And this function should not be necessary if the code-generator's [`pkg/generate/code.SetSDK` generator function](https://github.com/aws-controllers-k8s/code-generator/blob/843e3dd57998a61a0cd460de4da6ea1467a6f036/pkg/generate/code/set_sdk.go#L75) understood that for ReadMany operations, if it finds a field on the input shape that is the plural of an identifier field (in this case, VPCID -> VpcIds) then it should populate the input shape for the ReadMany operation with a slice of one element containing the resource's identifier field.

We can work on adding this functionality (we need it for S3 as well)

2021-08-04 14:02 UTC, brycahta commented on pkg/resource/vpc/hooks.go
> +// fields in the input shape are missing meaning AWS resource is
good call too much 🍝

2021-08-04 14:08 UTC, brycahta commented on apis/v1alpha1/types.go
> +	DpdTimeoutAction     *string `json:"dpdTimeoutAction,omitempty"`
when you say normalized does that mean it should be aligned with go styling?

2021-08-04 15:04 UTC, jaypipes commented on apis/v1alpha1/types.go
> +	DpdTimeoutAction     *string `json:"dpdTimeoutAction,omitempty"`
Yeah, initialisms should be capitalized fully when exported and lowercases fully when not exported according to Go style guidelines: https://github.com/golang/go/wiki/CodeReviewComments#initialisms

2021-08-04 17:16 UTC, RedbackThomson commented
/test ec2-kind-e2e
/test ec2-unit-test

2021-08-04 17:50 UTC, RedbackThomson commented
Pod initialising timed out? Weird

/retest ec2-kind-e2e

2021-08-04 17:51 UTC, RedbackThomson commented
Pod initialising timed out? Weird

/retest

2021-08-04 18:29 UTC, RedbackThomson commented
/retest

2021-08-04 18:52 UTC, RedbackThomson commented
Added the EC2 test role
/retest

2021-08-06 20:42 UTC, jaypipes approved these changes
Nice. :+1:

2021-08-06 20:43 UTC, jaypipes commented
/lgtm

2021-08-06 20:43 UTC, merged