VPC Flow Logs feature
aws-controllers-k8s/ec2-controller pull request #120
Opened 2022-12-07 17:15 UTC by p3nda

Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/1560

Description of changes:

Added support to create vpc flow logs via the EC2 ACK Controller. 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-12-07 20:06 UTC, LikithaVemulapalli requested changes
Hello, thanks for the contribution. I added few inline comments, could you please review them, and I couldn't see any updates to `VPC` like custom hook code or in `generator.yaml`, We need to add custom code in order to update/add `CreateFlowLogs` .

2022-12-08 18:47 UTC, A-Hilaly commented
/ok-to-test

2022-12-08 21:00 UTC, p3nda commented on apis/v1alpha1/generator.yaml
> +  CreateFlowLogs:
so i removed everything from apis/v1alpha1/generator.yaml and added everything to generator.yaml in the root and it auto generated back in apis/v1alpha1/generator.yaml just a heads up. Is there a way to prevent that, or is it expected behavior?

2022-12-08 21:01 UTC, p3nda commented
/retest

2022-12-08 21:16 UTC, LikithaVemulapalli commented on apis/v1alpha1/generator.yaml
> +  CreateFlowLogs:
It is expected behavior!

2022-12-08 22:30 UTC, p3nda commented
Closing for now - will resubmit at a later time

2022-12-08 22:30 UTC, closed without merging