VPC Flowlogs feature implementation
aws-controllers-k8s/ec2-controller pull request #138
Opened 2023-06-06 22:59 UTC by nnbu

This change implements flowlogs in ec2 operator.
It adds e2e tests for the flowlogs feature.

Issue #:  https://github.com/aws-controllers-k8s/community/issues/1560

Description of changes:

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-06-06 23:15 UTC, nnbu commented
Please refer my another PR (and the comment) which is created so that code-generator generates correct code for flow-logs.

https://github.com/aws-controllers-k8s/code-generator/pull/452#issuecomment-1579581579

2023-06-07 15:27 UTC, jaypipes requested changes

2023-06-07 15:27 UTC, jaypipes commented on helm/Chart.yaml
> +version: 0.0.0-non-release-version
hmm, this is not right :) I think you need to fetch all tags and rebase on main before running `make build-controller`.

Do this:

```
git checkout main && git fetch --all --tags && git rebase upstream/main
```

then git checkout the branch that this PR is in locally:

```
git checkout <YOUR_BRANCH_NAME>
```

and rebase onto main:

```
git rebase main
```

That should bring you up to date with the latest ec2-controller code...

2023-06-07 15:27 UTC, jaypipes commented on helm/Chart.yaml
> +version: 0.0.0-non-release-version
You will also want to rebase your `code-generator` repository onto main after fetching the latest too...

2023-06-07 15:27 UTC, jaypipes commented on templates/hooks/flow_logs/sdk_create_post_build_request.go.tpl
Please name this `templates/hooks/flow_log/sdk_create_post_build_request.go.tpl` (singular resource name, not plural :) )

2023-06-07 15:27 UTC, jaypipes commented on templates/hooks/flow_logs/sdk_file_end.go.tpl
Please name this `templates/hooks/flow_log/sdk_file_end.go.tpl` (singular resource name, not plural :) )

2023-06-07 15:27 UTC, jaypipes commented on test/e2e/bootstrap_resources.py
> +    FunctionsBucket: Bucket
Can you name this `FlowLogsBucket`? I think you may have copied this from the lambda-controller?

2023-06-07 15:27 UTC, jaypipes commented on test/e2e/service_bootstrap.py
> +            "ack-ec2-controller-tests",
maybe call this `ack-ec2-controller-flow-log-tests`.

Keep in mind bucket names are globally unique :)

2023-06-07 20:57 UTC, nnbu commented on generator.yaml
> +    - CreateFlowLogsInput.DryRun
done

2023-06-07 21:13 UTC, nnbu commented on generator.yaml
> +        template_path: hooks/dhcp_options/sdk_create_post_build_request.go.tpl
done

2023-06-07 21:14 UTC, nnbu commented on generator.yaml
> +        template_path: hooks/dhcp_options/sdk_file_end.go.tpl
done

2023-06-07 21:14 UTC, nnbu commented on templates/hooks/flow_logs/sdk_create_post_build_request.go.tpl
done

2023-06-07 21:14 UTC, nnbu commented on templates/hooks/flow_logs/sdk_file_end.go.tpl
done

2023-06-07 21:14 UTC, nnbu commented on test/e2e/service_bootstrap.py
> +            "ack-ec2-controller-tests",
done

2023-06-07 21:18 UTC, nnbu commented on helm/Chart.yaml
> +version: 0.0.0-non-release-version
I tried these steps. But the generated code always has version as '0.0.0-non-release-version'.

2023-06-07 21:31 UTC, nnbu commented on helm/Chart.yaml
> +version: 0.0.0-non-release-version
RELEASE_VERSION seems to get initialized in https://github.com/aws-controllers-k8s/code-generator/blob/main/scripts/build-controller-release.sh#L159

```
RELEASE_VERSION=${RELEASE_VERSION:-$(git describe --tags --abbrev=0 2>/dev/null || echo $NON_RELEASE_VERSION)}
```

So, I tried executing `git describe --tags` in my code-generator repo. But I get no tags.
```
code-generator % git checkout main && git fetch --all --tags && git rebase origin/main  
Already on 'main'
Your branch is up to date with 'origin/main'.
Current branch main is up to date.
code-generator % git describe --tags
fatal: No names found, cannot describe anything.
```

2023-06-07 21:55 UTC, nnbu commented on helm/Chart.yaml
> +version: 0.0.0-non-release-version
I had missed these steps
```
git remote add upstream git@github.com:aws-controllers-k8s/$REPO
git fetch --all
```

With this done, now release is correctly updated.

2023-06-08 14:06 UTC, jaypipes requested changes

2023-06-08 14:06 UTC, jaypipes commented on apis/v1alpha1/flow_log.go
> +	FlowLogIDs []*string `json:"flowLogIDs,omitempty"`
You will need to add a tiny bit of custom code in `sdk_read_one_post_set_output` to set the `Status.ID` field to the returned value of `*resp.FlowLogIds[0]` of course, but then you won't need to do things like this in `hooks.go`:

```go
resourceId := []*string{latest.ko.Status.FlowLogIDs[0]}
```

2023-06-08 14:06 UTC, jaypipes commented on pkg/resource/flow_log/hooks.go
> +func (rm *resourceManager) customUpdateFlowLogs(
Recommend renaming this to `customUpdateFlowLog` since we want to make clear that we're treating this "pluralized resource" as a singular resource.

2023-06-08 14:06 UTC, jaypipes commented on pkg/resource/flow_log/hooks.go
> +	exit := rlog.Trace("rm.customUpdateFlowLog")
Luckily, you've got the singular already here :)

2023-06-08 14:06 UTC, jaypipes commented on test/e2e/tests/test_flow_logs.py
> +        assert not exists
in a future PR, you may want to add a test case that updates the flow log tags and exercises the `customUpdateFlowLog` function in `hooks.go`

2023-06-08 22:37 UTC, nnbu commented on apis/v1alpha1/flow_log.go
> +	FlowLogIDs []*string `json:"flowLogIDs,omitempty"`
I tried to follow this, but could not get it working.

```
resources:
  FlowLog:
    fields:
      ID:
        type: string
        is_primary_key: true
        is_read_only: true
```
This snippet does not generate a new field ID in apis/v1alpha1/flow_log.go. I must be missing something. I tried removing `is_arn_primary_key: true` as well. But then it fails with error 
```
error calling GoCodeSetResourceIdentifiers: could not find field with path ID for primary key ID
```

Could you guide what I am missing?

2023-06-08 22:42 UTC, nnbu commented on apis/v1alpha1/flow_log.go
> +	FlowLogIDs []*string `json:"flowLogIDs,omitempty"`
Also, could you tell me more about `sdk_read_one_post_set_output`? I am not sure about how is supposed to work. I think, it is related to `sdkFind`. But I did not understand what code I should add there and where that code will be injected inside `sdkFind` ?

2023-06-09 00:59 UTC, nnbu commented on apis/v1alpha1/flow_log.go
> +	FlowLogIDs []*string `json:"flowLogIDs,omitempty"`
Somehow, `sdk_read_many_post_set_output` hook is triggered, not `sdk_read_many_post_set_output` . I have following code in the hook which correctly gets injected at the end of `sdkFind`
```
    if found {
        ko.Status.ID = resp.FlowLogs[0].FlowLogId
    }
```

Now, the only issue is `ID` being added. The error is as mentioned in previous comment.
```
error calling GoCodeSetResourceIdentifiers: could not find field with path ID for primary key ID
```

2023-06-09 01:59 UTC, nnbu commented on apis/v1alpha1/flow_log.go
> +	FlowLogIDs []*string `json:"flowLogIDs,omitempty"`
I understand the dependencies about declaring new `field` in `generator.yaml`.
1. if the field is to go in `spec`, then you can declare using the way you declared (and of course, it cant be `is_read_only` then)
2. if the field is to go in `status` (as we would like), then it needs to have 'from' defined. https://github.com/aws-controllers-k8s/code-generator/blob/main/pkg/model/model.go#L252

So , I defined the field something like this:
```
+.    ID:
+        type: string
+        is_read_only: true
+        from:
+          operation: CreateFlowLogs
+          path: FlowLogIds
```

But for this to work, `FlowLogIds` can't be in 'ignore` section. `#- CreateFlowLogsOutput.FlowLogIds`.
If it is in `ignore` section, then `FlowLogIds` is not `shape.MemberRefs` at https://github.com/aws-controllers-k8s/code-generator/blob/main/pkg/model/sdk_api.go#L396

So, the newly added field `ID` is ignored and not added to `status` struct in generated api.

2023-06-09 08:40 UTC, nnbu commented on apis/v1alpha1/flow_log.go
> +	FlowLogIDs []*string `json:"flowLogIDs,omitempty"`
Another note here is, all flowlog apis CreateFlowLogs, DescribeFlowLogs, DeleteFlowLogs accept list of flowLogIds as parameter. https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DeleteFlowLogs.html

So, even if we convert `FlowLogIds` to `ID` in the `status`, we have to convert that back to list in `newListRequestPayload` and `newDeleteRequestPayload`.

So, I would like to keep `CreateFlowLogsResult.FlowLogIds` as it is. Let me know your thoughts.

2023-06-09 13:03 UTC, jaypipes commented on apis/v1alpha1/flow_log.go
> +	FlowLogIDs []*string `json:"flowLogIDs,omitempty"`
I don't see the point of keeping it a list when there will only ever be a single value in there. :)

2023-06-09 13:17 UTC, jaypipes commented on apis/v1alpha1/flow_log.go
> +	FlowLogIDs []*string `json:"flowLogIDs,omitempty"`
> Also, could you tell me more about `sdk_read_one_post_set_output`? I am not sure about how is supposed to work. I think, it is related to `sdkFind`. But I did not understand what code I should add there and where that code will be injected inside `sdkFind` ?

Yes, for each of the CRUD actions (`read_[one|many]`, `create`, `update` and `delete`) there is a corresponding custom code hook point called `sdk_$action_post_set_output` that is executed immediately after the response Output shape is processed and the custom resource's fields are set to values in that response output.

If we take a look at the `DHCPOptions` resource's `sdkFind` method, this line here:

https://github.com/aws-controllers-k8s/ec2-controller/blob/5d460dbad24e44a11e80a693fbd61d498820476b/pkg/resource/dhcp_options/sdk.go#L147

is where the `sdk_read_many_post_set_output` hook would be executed if there was one. It is an opportunity to override any fields on the [`ko`](https://github.com/aws-controllers-k8s/ec2-controller/blob/5d460dbad24e44a11e80a693fbd61d498820476b/pkg/resource/dhcp_options/sdk.go#L87) variable that represents the custom resource being returned from the function.

So, in the case of FlowLog, we could put the following code into the `sdk_read_many_post_set_output` custom code hook:

```go
ko.Status.ID = *resp.FlowLogs[0].ResourceId
```

because the [`DescribeFlowLogs`](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeFlowLogs.html) response uses the field name `ResourceId` instead of `FlowLogId` ( :( for consistency...).

In the `sdk_create_post_set_output` code hook, you'd do this:

```go
ko.Status.ID = *resp.FlowLogIds[0]
```

because the `CreateFlowLogs` response field is called `FlowLogIds`.

2023-06-09 17:31 UTC, nnbu commented on pkg/resource/flow_log/hooks.go
> +func (rm *resourceManager) customUpdateFlowLogs(
done

2023-06-09 17:31 UTC, nnbu commented on test/e2e/tests/test_flow_logs.py
> +        assert not exists
sure

2023-06-09 17:54 UTC, nnbu commented on apis/v1alpha1/flow_log.go
> +	FlowLogIDs []*string `json:"flowLogIDs,omitempty"`
> I don't see the point of keeping it a list when there will only ever be a single value in there. :)

After reviewing the CreateFlowLogs, DescribeFlowLogs, DeleteFlowLogs, we are working with lists always. e.g. CreateFlowLogs allows to create a list of of FlowLogsIds. 

So, I modified e2e tests as well to accommodate creation of multiple FlowLogIds. The e2e tests are passing.

I also changed this code 
```
resourceId := []*string{latest.ko.Status.FlowLogIDs[0]}
```
to
```
resourceId := latest.ko.Status.FlowLogIDs
```

So, I am no longer checking single FlowLogId.

2023-06-10 04:52 UTC, nnbu commented on apis/v1alpha1/flow_log.go
> +	FlowLogIDs []*string `json:"flowLogIDs,omitempty"`
As discussed over the chat, I have now converted FlowLogIds, ResourceIDs (list) to FlowLogId, ResourceID (single string)

2023-06-13 15:55 UTC, nnbu commented on generator.yaml
> +        is_primary_key: true
In fact it worked after this change in code-generator.
https://github.com/aws-controllers-k8s/code-generator/pull/453

2023-06-13 15:56 UTC, nnbu commented
/assign @jljaco

2023-06-13 16:19 UTC, jljaco commented
/ok-to-test

2023-06-14 16:00 UTC, LikithaVemulapalli requested changes

2023-06-14 16:00 UTC, LikithaVemulapalli commented on apis/v1alpha1/ack-generate-metadata.yaml
> +  version: v0.26.1-5-gb74f41d-dirty
This version shouldn't be tagged with dirty, could you try fetching the tags `git fetch --tags` in `code-generator` and regenerate the code. Thanks :)

2023-06-14 17:12 UTC, nnbu commented on apis/v1alpha1/ack-generate-metadata.yaml
> +  version: v0.26.1-5-gb74f41d-dirty
I missed it. I needed https://github.com/aws-controllers-k8s/code-generator/pull/453 to be merged before regenerating the code. Now, it is merged. and I have uploaded the change after new code generation.

2023-06-14 17:56 UTC, LikithaVemulapalli approved these changes
Great work @nnbu :)

2023-06-14 17:59 UTC, LikithaVemulapalli commented
/lgtm

2023-06-14 17:59 UTC, merged