Add Network ACL support in EC2 controller
aws-controllers-k8s/ec2-controller pull request #140
Opened 2023-06-19 11:07 UTC by nishant221

Issue (https://github.com/aws-controllers-k8s/community/issues/1559)

Description of changes:
Added support in EC2 controller for adding/updating/creating NACL.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-06-20 19:00 UTC, RedbackThomson requested changes
Great job with this. Mostly some nitpicks. Would you mind also adding a test case, which uses the custom hook code?

2023-06-21 20:30 UTC, nnbu requested changes

2023-06-21 20:30 UTC, nnbu commented on apis/v1alpha1/generator.yaml
> +    - CreateNetworkAclInput.ClientToken
`CreateNetworkAcl` does not seem to have `ClientToken`. Do we need this line here? https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateNetworkAcl.html

2023-06-21 20:30 UTC, nnbu commented on apis/v1alpha1/generator.yaml
> +        #is_primary_key: true
nit: please remove the commented line `#is_primary_key: true`

2023-06-21 20:30 UTC, nnbu commented on config/crd/bases/ec2.services.k8s.aws_networkaclentries.yaml
> +  name: networkaclentries.ec2.services.k8s.aws
This file does not seem to be generated by code-generator, unless you add `netoworkAclEntry` resource in generator.yaml. Is this residual file to be removed?

2023-06-21 20:30 UTC, nnbu commented on apis/v1alpha1/ack-generate-metadata.yaml
> +  version: v0.26.1-7-ge9b6859-dirty
Could you update the tags in `code-generator` repo and rebuild this? `version` should not be `dirty`.

2023-06-22 04:40 UTC, nishant221 commented on apis/v1alpha1/generator.yaml
> +
Removed.

2023-06-22 04:40 UTC, nishant221 commented on pkg/resource/network_acl/hooks.go
> +	//ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
Removed.

2023-06-22 04:40 UTC, nishant221 commented on pkg/resource/network_acl/hooks.go
> +
Removed.

2023-06-22 04:41 UTC, nishant221 commented on pkg/resource/network_acl/hooks.go
> +	// // Checking latest for entries which has the same rule number as the entry in toAdd
Changed.

2023-06-22 04:42 UTC, nishant221 commented on pkg/resource/network_acl/hooks.go
> +		rlog.Debug("adding entries to nacl")
Removed `rlog.Debug` lines.

2023-06-22 04:42 UTC, nishant221 commented on apis/v1alpha1/generator.yaml
> +    - CreateNetworkAclInput.ClientToken
Removed.

2023-06-22 04:43 UTC, nishant221 commented on apis/v1alpha1/generator.yaml
> +        #is_primary_key: true
Removed.

2023-06-22 04:47 UTC, nishant221 commented on config/crd/bases/ec2.services.k8s.aws_networkaclentries.yaml
> +  name: networkaclentries.ec2.services.k8s.aws
Yes. This file is a residual one. Thanks for notifying. Removed the file.

2023-06-22 04:48 UTC, nishant221 commented on apis/v1alpha1/ack-generate-metadata.yaml
> +  version: v0.26.1-7-ge9b6859-dirty
Fixed this.

2023-06-22 06:28 UTC, nishant221 commented on pkg/resource/network_acl/hooks.go
> +	}
Encapsulated.

2023-06-22 06:29 UTC, nishant221 commented on pkg/resource/network_acl/hooks.go
> +		if *((*desiredEntry).RuleNumber) == int64(32767) {
Moved the value to a variable.

2023-06-22 06:30 UTC, nishant221 commented
Incorporated some of the feedbacks. Working on rest of them and on adding the test cases.

2023-06-27 06:16 UTC, nishant221 commented
@RedbackThomson Added e2e-tests as well. Will it be possible to add `ok-to-test` on this PR ?

2023-06-27 16:03 UTC, nishant221 commented on pkg/resource/network_acl/hooks.go
> +func computeTagsDelta(
Modified as per the suggestion.

2023-06-27 16:18 UTC, nishant221 commented on apis/v1alpha1/network_acl.go
> +	NetworkACLID *string `json:"networkACLID,omitempty"`
Have a small doubt on this one. Is this what we are referring to https://github.com/aws-controllers-k8s/ec2-controller/pull/140/files#diff-e8312348bafc4b9c54ba32ead53d9e158a234f574eeebe73c846c20d3548e6b0R524-R527 ?

2023-06-27 16:19 UTC, nishant221 commented
@RedbackThomson Incorporated all the feedbacks and added e2e tests as well. 
There is only one feedback that I have added a follow-up comment on to understand it better.

Kindly have a look.
Thanks

2023-06-27 17:58 UTC, nnbu commented on apis/v1alpha1/network_acl.go
> +	NetworkACLID *string `json:"networkACLID,omitempty"`
I think, @RedbackThomson is referring to [renaming](https://aws-controllers-k8s.github.io/community/docs/contributor-docs/code-generator-config/#renames-renaming-things) the field using `rename` directive. 

The code you pointed is used for [printing](https://aws-controllers-k8s.github.io/community/docs/contributor-docs/code-generator-config/#print-controlling-a-fields-output-as-printer-columns-in-kubectl-get).

2023-06-27 18:02 UTC, RedbackThomson commented on apis/v1alpha1/network_acl.go
> +	NetworkACLID *string `json:"networkACLID,omitempty"`
@nnbu Is correct. I don't think it's necessary to print the ID (although we could, too), but I'd at least like to see it renamed.

2023-06-27 18:02 UTC, RedbackThomson commented
/ok-to-test

2023-06-27 18:03 UTC, RedbackThomson commented on test/e2e/tests/test_network_acl.py
> +    @pytest.mark.resource_data({'tag_key': 'initialtagkey', 'tag_value': 'initialtagvalue'})
This is interesting. Why did you choose this method over simply hardcoding it?

2023-06-27 18:16 UTC, nnbu commented on apis/v1alpha1/generator.yaml
> +          list_of: NetworkAclAssociation
I don't any logic which kicks in if `Association` is specified in the spec. Do you plan to add this support in a future PR?

2023-06-29 11:27 UTC, nishant221 commented
Working on fixing e2e test errors and incorporating leftover feedbacks.

2023-07-03 15:47 UTC, nishant221 commented
e2e-tests are now passing.

2023-07-04 10:03 UTC, nishant221 commented on apis/v1alpha1/network_acl.go
> +	NetworkACLID *string `json:"networkACLID,omitempty"`
@RedbackThomson  As suggested, renamed `NetworkAclID` to `ID`.

2023-07-04 10:04 UTC, nishant221 commented on test/e2e/tests/test_network_acl.py
> +    @pytest.mark.resource_data({'tag_key': 'initialtagkey', 'tag_value': 'initialtagvalue'})
Yes, we can hardcode it as well. Tried to follow code uniformity with other resources test cases (e.g. https://github.com/aws-controllers-k8s/ec2-controller/blob/main/test/e2e/tests/test_nat_gateway.py#L155 )

2023-07-04 10:05 UTC, nishant221 commented on apis/v1alpha1/generator.yaml
> +          list_of: NetworkAclAssociation
@nnbu Yes, planning on covering it up in a follow-up PR.

2023-07-04 10:06 UTC, nishant221 commented
@RedbackThomson Incorporated all the feedbacks and e2e tests are also now passing. Kindly have a look at your convenience .
Thanks

2023-07-06 12:41 UTC, nishant221 commented on apis/v1alpha1/generator.yaml
> +          list_of: NetworkAclAssociation
@nnbu Added support for `Association` as well with the commit : https://github.com/aws-controllers-k8s/ec2-controller/pull/140/commits/58a814bf7c14540958728fd08a4e6667ccdaf692

2023-07-06 12:43 UTC, nishant221 commented
@RedbackThomson Added support for `Association` as well with the commit : https://github.com/aws-controllers-k8s/ec2-controller/pull/140/commits/58a814bf7c14540958728fd08a4e6667ccdaf692
Kindly have a look at your convenience. 



We use NACL in our infra and it will be of great help for us if this can be reviewed/merged :)

2023-07-06 16:53 UTC, RedbackThomson requested changes

2023-07-06 16:53 UTC, RedbackThomson commented on pkg/resource/network_acl/hooks.go
> +) (sdktags []*svcsdk.Tag) {
nit: You have 2 comment blocks, and please remove the spacing around the parameters

2023-07-06 16:53 UTC, RedbackThomson commented on pkg/resource/network_acl/hooks.go
> +func compareTags(
We aren't using this anymore? Please delete

2023-07-06 16:53 UTC, RedbackThomson commented on pkg/resource/network_acl/hooks.go
> +		if err := rm.syncRules(ctx, desired, latest); err != nil {
Any particular reason you didn't call this `syncEntries`?

2023-07-06 16:53 UTC, RedbackThomson commented on pkg/resource/network_acl/hooks.go
> +func (rm *resourceManager) createRules(
Same as above - why not `createEntries`?

2023-07-06 16:53 UTC, RedbackThomson commented on pkg/resource/network_acl/hooks.go
> +	if r.ko.Spec.Entries != nil {
This should be checking for `r.ko.Spec.Associations`

2023-07-06 16:53 UTC, RedbackThomson commented on pkg/resource/network_acl/hooks.go
> +				latest_associations[*association.SubnetID] = "SubnetID"
Please move magic strings into consts at the top of the file

2023-07-06 16:53 UTC, RedbackThomson commented on pkg/resource/network_acl/hooks.go
> +	y := lo.OmitByKeys(latest_associations, lo.Keys(desired_associations))
Please rename this variable to something more understandable

2023-07-06 16:53 UTC, RedbackThomson commented on pkg/resource/network_acl/hooks.go
> +	to_Add := lo.OmitByKeys(desired_associations, lo.Keys(latest_associations))
nit: Could you add a little comment above this just explaining what all of these omits and picks achieve?

2023-07-06 16:53 UTC, RedbackThomson commented on pkg/resource/network_acl/hooks.go
> +				return errors.New("unexpected output from describenetworkacls for the given subnet")
```suggestion
return errors.New("unexpected output from DescribeNetworkAcls for the given subnet")
```

2023-07-06 16:53 UTC, RedbackThomson commented on pkg/resource/network_acl/hooks.go
> +			} else {
nit: Don't need `else` after a `return`

2023-07-06 16:53 UTC, RedbackThomson commented on pkg/resource/network_acl/hooks.go
> +			rm.metrics.RecordAPICall("DESCRIBE", "DescribeNetworkAcls", err)
```suggestion
rm.metrics.RecordAPICall("READ_MANY", "DescribeNetworkAcls", err)
```

2023-07-06 16:53 UTC, RedbackThomson commented on pkg/resource/network_acl/hooks.go
> +	rm.metrics.RecordAPICall("DESCRIBE", "DescribeNetworkAcls", err)
```suggestion
rm.metrics.RecordAPICall("READ_MANY", "DescribeNetworkAcls", err)
```

2023-07-06 16:53 UTC, RedbackThomson commented on pkg/resource/network_acl/hooks.go
> +		return errors.New("could not determine")
Please finish this error message

2023-07-06 16:53 UTC, RedbackThomson commented on pkg/resource/network_acl/hooks.go
> +		input := &svcsdk.ReplaceNetworkAclAssociationInput{}
I feel like this logic is very long for 1 method - perhaps we could break it up into `upsertNewAssociations` and `deleteOldAssociations`?

2023-07-06 16:53 UTC, RedbackThomson commented on pkg/resource/network_acl/hooks.go
> +}
Please use `lo.ToPtr`

2023-07-06 16:53 UTC, RedbackThomson commented on pkg/resource/network_acl/hooks.go
> +var defaultRuleNumber = 32767
nit: Use proper case for consts:
```suggestion
var DefaultRuleNumber = 32767
```

2023-07-06 16:53 UTC, RedbackThomson commented on pkg/resource/network_acl/hooks.go
> +	}
It seems this logic is just checking for uniqueness? We can use `lo.UniqBy` instead

2023-07-06 16:53 UTC, RedbackThomson commented on pkg/resource/network_acl/hooks.go
> +	rm.metrics.RecordAPICall("CREATE", "CreateNetworkAclEntry", err)
```suggestion
rm.metrics.RecordAPICall("UPDATE", "CreateNetworkAclEntry", err)
```

2023-07-06 16:53 UTC, RedbackThomson commented on pkg/resource/network_acl/hooks.go
> +	rm.metrics.RecordAPICall("REPLACE", "ReplaceNetworkAclEntry", err)
```suggestion
rm.metrics.RecordAPICall("UPDATE", "ReplaceNetworkAclEntry", err)
```

2023-07-06 16:53 UTC, RedbackThomson commented on pkg/resource/network_acl/hooks.go
> +	rm.metrics.RecordAPICall("DELETE", "DeleteNetworkAclEntry", err)
```suggestion
rm.metrics.RecordAPICall("UPDATE", "DeleteNetworkAclEntry", err)
```

2023-07-06 16:53 UTC, RedbackThomson commented on test/e2e/tests/helper.py
> +            print(entries)
Please remove

2023-07-06 16:53 UTC, RedbackThomson commented on test/e2e/tests/test_network_acl.py
> +    #replacements["TAG_VALUE"] = resource_name
Please clean

2023-07-06 16:53 UTC, RedbackThomson commented on test/e2e/tests/test_network_acl.py
> +    @pytest.mark.resource_data({'tag_key': 'initialtagkey', 'tag_value': 'initialtagvalue'})
I don't think it adds anything to the tests, for now, and adds complexity into the fixture logic. Could we please hard code it instead?

2023-07-06 16:53 UTC, RedbackThomson commented on test/e2e/tests/test_network_acl.py
> +        print(resource)
Please clean

2023-07-06 16:53 UTC, RedbackThomson commented on test/e2e/tests/test_network_acl.py
> +        print(network_acl)
Clean

2023-07-06 16:53 UTC, RedbackThomson commented on test/e2e/tests/test_network_acl.py
> +                "spec": {"tags": []},
Maybe we can add new associations and entries to test their update code path?

2023-07-06 18:23 UTC, nishant221 commented on pkg/resource/network_acl/hooks.go
> +) (sdktags []*svcsdk.Tag) {
Fixed.

2023-07-06 18:24 UTC, nishant221 commented on pkg/resource/network_acl/hooks.go
> +func (rm *resourceManager) createRules(
Yes, `createEntries ` makes more sense. Changed.

2023-07-06 18:24 UTC, nishant221 commented on pkg/resource/network_acl/hooks.go
> +	if r.ko.Spec.Entries != nil {
Changed.

2023-07-06 18:25 UTC, nishant221 commented on pkg/resource/network_acl/hooks.go
> +				latest_associations[*association.SubnetID] = "SubnetID"
Moved.

2023-07-06 18:25 UTC, nishant221 commented on pkg/resource/network_acl/hooks.go
> +	y := lo.OmitByKeys(latest_associations, lo.Keys(desired_associations))
Changed.

2023-07-06 18:25 UTC, nishant221 commented on pkg/resource/network_acl/hooks.go
> +	to_Add := lo.OmitByKeys(desired_associations, lo.Keys(latest_associations))
Added.

2023-07-06 18:25 UTC, nishant221 commented on pkg/resource/network_acl/hooks.go
> +				return errors.New("unexpected output from describenetworkacls for the given subnet")
Changed.

2023-07-06 18:25 UTC, nishant221 commented on pkg/resource/network_acl/hooks.go
> +			} else {
Removed.

2023-07-06 18:25 UTC, nishant221 commented on pkg/resource/network_acl/hooks.go
> +			rm.metrics.RecordAPICall("DESCRIBE", "DescribeNetworkAcls", err)
Changed.

2023-07-06 18:26 UTC, nishant221 commented on pkg/resource/network_acl/hooks.go
> +	rm.metrics.RecordAPICall("DESCRIBE", "DescribeNetworkAcls", err)
Changed.

2023-07-06 18:26 UTC, nishant221 commented on pkg/resource/network_acl/hooks.go
> +		return errors.New("could not determine")
Modified.

2023-07-06 18:26 UTC, nishant221 commented on pkg/resource/network_acl/hooks.go
> +}
Changed `toStrPtr` to `lo.ToPtr`

2023-07-06 18:26 UTC, nishant221 commented on pkg/resource/network_acl/hooks.go
> +var defaultRuleNumber = 32767
Changed.

2023-07-06 18:26 UTC, nishant221 commented on pkg/resource/network_acl/hooks.go
> +	rm.metrics.RecordAPICall("CREATE", "CreateNetworkAclEntry", err)
Changed.

2023-07-06 18:27 UTC, nishant221 commented on pkg/resource/network_acl/hooks.go
> +	rm.metrics.RecordAPICall("REPLACE", "ReplaceNetworkAclEntry", err)
Changed.

2023-07-06 18:27 UTC, nishant221 commented on pkg/resource/network_acl/hooks.go
> +	rm.metrics.RecordAPICall("DELETE", "DeleteNetworkAclEntry", err)
Changed.

2023-07-06 18:27 UTC, nishant221 commented on test/e2e/tests/helper.py
> +            print(entries)
Cleaned.

2023-07-06 18:27 UTC, nishant221 commented on test/e2e/tests/test_network_acl.py
> +    #replacements["TAG_VALUE"] = resource_name
Cleaned.

2023-07-06 18:27 UTC, nishant221 commented on test/e2e/tests/test_network_acl.py
> +        print(resource)
Cleaned.

2023-07-06 18:27 UTC, nishant221 commented on test/e2e/tests/test_network_acl.py
> +        print(network_acl)
Done.

2023-07-06 19:18 UTC, nishant221 commented on test/e2e/tests/test_network_acl.py
> +    @pytest.mark.resource_data({'tag_key': 'initialtagkey', 'tag_value': 'initialtagvalue'})
HardCoded.

2023-07-06 19:19 UTC, nishant221 commented on pkg/resource/network_acl/hooks.go
> +		input := &svcsdk.ReplaceNetworkAclAssociationInput{}
Function splitted into `upsertNewAssociations` and `deleteOldAssociations`

2023-07-06 19:22 UTC, nishant221 commented on pkg/resource/network_acl/hooks.go
> +	}
Modified the logic to use `lo.UniqBy`

2023-07-06 20:11 UTC, nishant221 commented on pkg/resource/network_acl/hooks.go
> +func compareTags(
We are using it `delta.go`.

2023-07-06 20:23 UTC, nishant221 commented on test/e2e/tests/test_network_acl.py
> +                "spec": {"tags": []},
Added required associations test as well.

2023-07-06 20:25 UTC, nishant221 commented
@RedbackThomson Thank you for reviewing this. I have incorporated all the mentioned feedbacks and suggestions. Kindly have a look at your convenience. 
Thanks

2023-07-06 20:35 UTC, A-Hilaly commented on pkg/resource/network_acl/sdk.go
> +	}
Not sure but maybe we also also need to set `status.ID` in the above? in case we try to adopt this resource, `requiredFieldsMissingFromReadManyInput` will always return false causing the `skdFidn` to return `ack.NotFound`.

2023-07-06 20:52 UTC, A-Hilaly reviewed
This is very good stuff!! Thank you @nishant221 !!
I have few nit/comments below

2023-07-06 20:52 UTC, A-Hilaly commented on pkg/resource/network_acl/hooks.go
> +		}
Why is this need with Entries but not associations? maybe it useful to call it right before existing `customUpdateNetworkAcl` ?

2023-07-06 20:52 UTC, A-Hilaly commented on pkg/resource/network_acl/hooks.go
> +			dna_output, err := rm.sdkapi.DescribeNetworkAclsWithContext(ctx, dna_input)
nit: can we continue using camel case for go code? `dna_output` => `dnaOutput`. There are multiple similar cases in this file

2023-07-06 20:52 UTC, A-Hilaly commented on pkg/resource/network_acl/hooks.go
> +				return errors.New("unexpected output from describenetworkacls for the given subnet")
nit: L300 better be called after L301

2023-07-06 20:52 UTC, A-Hilaly commented on templates/hooks/network_acl/sdk_create_post_set_output.go.tpl
> +	}
Is it possible that we reach this case?

2023-07-06 20:52 UTC, A-Hilaly commented on templates/hooks/network_acl/sdk_create_post_set_output.go.tpl
> +	}
Is this operation necessary? i see that `sdkCreate` accepts tags. Maybe it doesn't "really" create them (i have seen a similar case before :) )?

2023-07-07 07:39 UTC, nishant221 commented on pkg/resource/network_acl/hooks.go
> +		}
Done.

2023-07-07 07:39 UTC, nishant221 commented on pkg/resource/network_acl/hooks.go
> +				return errors.New("unexpected output from describenetworkacls for the given subnet")
Modified.

2023-07-07 07:39 UTC, nishant221 commented on templates/hooks/network_acl/sdk_create_post_set_output.go.tpl
> +	}
I tested without this . I don't think we need this. Removed.

2023-07-07 09:51 UTC, nishant221 commented
/test ec2-kind-e2e

2023-07-07 09:55 UTC, nishant221 commented on templates/hooks/network_acl/sdk_create_post_set_output.go.tpl
> +	}
It's unlikely but added this to cover any edge case where `CreateNetworkAcl` failed to create NACL and errors are not caught by [this](https://github.com/aws-controllers-k8s/ec2-controller/pull/140/files#diff-1fb337f82754cf5c7ea58918ef9328698030a802e4adf859fe0f7b5a01216e68R246).

2023-07-07 10:52 UTC, nishant221 commented on pkg/resource/network_acl/sdk.go
> +	}
Not sure on this. I tried to adopt a nacl resource via below and it works :
```
apiVersion: services.k8s.aws/v1alpha1
kind: AdoptedResource
metadata:
  name: test-nacl-adopted
spec:
  aws:
    nameOrID: <nacl_id>
  kubernetes:
    group: ec2.services.k8s.aws
    kind: NetworkACL
```

```
Status:
  Ack Resource Metadata:
    Owner Account ID:  <account-id>
    Region:            us-west-2
  Conditions:
    Last Transition Time:  2023-07-07T10:02:27Z
    Message:               Resource synced successfully
    Reason:
    Status:                True
    Type:                  ACK.ResourceSynced
  Id:                      <nacl_id>
  Is Default:              false
  Owner ID:                <account-id>
Events:                    <none>
```

2023-07-07 13:07 UTC, nishant221 commented on pkg/resource/network_acl/hooks.go
> +			dna_output, err := rm.sdkapi.DescribeNetworkAclsWithContext(ctx, dna_input)
Fixed these.

2023-07-07 13:10 UTC, nishant221 commented
@RedbackThomson / @A-Hilaly Made all the changes as per the feedbacks and tried to provide answer for the couple of questions. Also, modified e2e test to cover remaining code path as well.

Kindly have a look.

2023-07-07 13:48 UTC, nishant221 commented
/test ec2-kind-e2e

2023-07-07 14:13 UTC, nishant221 commented
/test ec2-kind-e2e

2023-07-07 16:46 UTC, A-Hilaly approved these changes
Neat!! :+1:
/approve
/cc @RedbackThomson

2023-07-07 16:46 UTC, A-Hilaly commented
/test all

2023-07-08 02:19 UTC, nishant221 commented
/test ec2-kind-e2e

2023-07-10 17:23 UTC, RedbackThomson commented on pkg/resource/network_acl/hooks.go
> +			rm.metrics.RecordAPICall("DESCRIBE", "DescribeNetworkAcls", err)
Don't see this change

2023-07-10 17:23 UTC, RedbackThomson commented on pkg/resource/network_acl/hooks.go
> +				return errors.New("unexpected output from describenetworkacls for the given subnet")
Also don't see this

2023-07-10 17:46 UTC, nishant221 commented on pkg/resource/network_acl/hooks.go
> +			rm.metrics.RecordAPICall("DESCRIBE", "DescribeNetworkAcls", err)
Apologies for missing this one. Pushed the required changes now.

2023-07-10 18:04 UTC, merged