Generate Transit Gateway using ACK runtime `v0.15.1`
aws-controllers-k8s/ec2-controller pull request #17
Opened 2021-10-18 23:32 UTC by bwagner5

Issue #, if available:
https://github.com/aws-controllers-k8s/community/issues/489

Description of changes:

process is broken up into commits between the generated and manual steps.

 - Generate Transit Gateway resource Create and Delete
 - Tests for Create and Delete (the sleeps on TGW create and delete are lengthy because the resource takes so long to be created and will error out if a delete is attempted while in a "pending" state)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-10-19 14:11 UTC, brycahta requested changes
First resource looking great!! 🎉 

Just add that comment and we're sending this; also updated PR title for clarity

2021-10-19 14:11 UTC, brycahta commented on apis/v1alpha1/types.go
> +	EnaSupport            *bool        `json:"enaSupport,omitempty"`
Ena should be added to initialism list (at some point). Example PR: https://github.com/aws-controllers-k8s/code-generator/pull/147

2021-10-19 14:11 UTC, brycahta commented on apis/v1alpha1/types.go
> +	VPNEcmpSupport                 *string   `json:"vpnEcmpSupport,omitempty"`
is Ecmp supposed to be an initialism?

2021-10-19 14:11 UTC, brycahta commented on test/e2e/tests/test_transit_gateway.py
> +CREATE_WAIT_AFTER_SECONDS = 90
Because this seems key to passing the test, could you add a comment either why it's set to these values and/or telling others not to change it?

2021-10-19 14:11 UTC, brycahta commented on test/e2e/tests/test_transit_gateway.py
> +        _, deleted = k8s.delete_custom_resource(ref, 2, 5)
what are the `2,5` params for?

2021-10-19 14:28 UTC, bwagner5 commented on apis/v1alpha1/types.go
> +	VPNEcmpSupport                 *string   `json:"vpnEcmpSupport,omitempty"`
yep, Equal-Cost Multi-Path

2021-10-19 19:04 UTC, bwagner5 commented
/retest

2021-10-19 23:23 UTC, vijtrip2 commented
/test ec2-kind-e2e

2021-10-20 13:20 UTC, brycahta approved these changes
/lgtm

2021-10-20 13:21 UTC, merged