Add `ElasticIP` CRD
aws-controllers-k8s/ec2-controller pull request #39
Opened 2022-03-14 22:41 UTC by RedbackThomson

Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/1218

Description of changes:
Creates the `ElasticIP` custom resource, from `AllocateAddress` and `DeallocateAddress`. This API uses either `AllocationID` or `PublicIP` as the identifier depending on whether the domain is set to `"vpc"` (for EC2-VPC) or otherwise (for EC2-Classic), respectively. For the adoption, I have chosen to set `AllocationID` as the primary key for now, since EC2-VPC is the recommended method for managing resources in EC2.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-03-14 22:42 UTC, RedbackThomson commented
@brycahta What do you think of the name? Should this be renamed to `ElasticIPAddress` or even just `Address`? I used the term `ElasticIP` since the console shows these resources as `Elastic IP Addresses`.

2022-03-14 22:49 UTC, RedbackThomson commented
/test ec2-kind-e2e

2022-03-15 03:32 UTC, vijtrip2 commented
/approve

2022-03-15 11:55 UTC, A-Hilaly reviewed
Looks good! Left one comment below

2022-03-15 11:55 UTC, A-Hilaly commented on config/crd/bases/ec2.services.k8s.aws_elasticips.yaml
> +    kind: ElasticIP
This is a duplicate file of `config/crd/bases/ec2.services.k8s.aws_elasticipaddresses.yaml`

2022-03-15 14:40 UTC, jaypipes requested changes

2022-03-15 14:40 UTC, jaypipes commented on apis/v1alpha1/elastic_ip_address.go
> +	TagSpecifications []*TagSpecification `json:"tagSpecifications,omitempty"`
Can we rename this just `Tags`?

2022-03-15 14:40 UTC, jaypipes commented on apis/v1alpha1/elastic_ip_address.go
> +	Domain *string `json:"domain,omitempty"`
Recommend removing this field (since we should not support EC2-Classic) and always override it to `vpc`

2022-03-15 15:19 UTC, brycahta requested changes

2022-03-15 15:19 UTC, brycahta commented on generator.yaml
> +    custom_check_required_fields_missing_method: customCheckRequiredFieldsMissing
Is it necessary to use `custom_check_required_fields_missing_method` here vs. resource having a pre_build_request hook?

2022-03-15 15:19 UTC, brycahta commented on generator.yaml
> +      # PublicIP and AllocationID are two ways of identifying the same resource
Per the comment on line 19, we won't be supporting ec2-classic because it will be deprecated soon™️

2022-03-15 15:19 UTC, brycahta commented on helm/crds/ec2.services.k8s.aws_elasticips.yaml
> +
leftover file from the rename?

2022-03-15 16:38 UTC, RedbackThomson commented on apis/v1alpha1/elastic_ip_address.go
> +	TagSpecifications []*TagSpecification `json:"tagSpecifications,omitempty"`
All the other EC2 resources have this as `TagSpecifications` as well. It's not a slice of key-value pairs like you would expect. The format is instead:
```yaml
spec:
  tagSpecifications:
  - resourceType: "elastic-ip"
     tags:
     - key: Name
       value: "My-Elastic-IP"   
```

Replace the `resourceType` field with `"vpc"`, `"nat-gateway"`, etc. So they're at least all consistently inconsistent with the standard practice. I think these should all be replaced with a `Tags` field and the `resourceType` inject by the controller before making a request.

2022-03-15 16:39 UTC, RedbackThomson commented on generator.yaml
> +    custom_check_required_fields_missing_method: customCheckRequiredFieldsMissing
It just exits a little bit earlier, and simplifies the logic in that code block. But no, I could reduce it down to one.

2022-03-15 16:48 UTC, brycahta commented on generator.yaml
> +    custom_check_required_fields_missing_method: customCheckRequiredFieldsMissing
Gotcha, in that case could you move it to a hook? That would align with existing code and long-term plan to move away from operation-centric configs (I know some are necessary atm).

2022-03-16 16:05 UTC, brycahta approved these changes
looks solid to me

2022-03-16 16:33 UTC, jaypipes commented on generator.yaml
> +          name: PUBLIC-IP
We wanted to remove this, right?

2022-03-16 16:35 UTC, RedbackThomson commented on generator.yaml
> +          name: PUBLIC-IP
Is it not still something that's relevant,even for EC2-VPC? I thought the point of an Elastic IP address was that you were reserving this Public IP within the AWS IP space. I just don't use it as the identifier anywhere.

2022-03-21 19:04 UTC, brycahta approved these changes
/lgtm

2022-03-21 19:12 UTC, merged