Add route table assocations to `Subnet`
aws-controllers-k8s/ec2-controller pull request #45
Opened 2022-03-25 00:20 UTC by RedbackThomson

Closes https://github.com/aws-controllers-k8s/community/issues/1219

Description of changes:
Generates the `Subnet` CRD with a new custom field `RouteTables`, which represent an array of route table IDs. Route tables are associated with the `Subnet` using the `AssociateRouteTable` API call, and then updated by deleting the association (using `DisassociateRouteTable`) and re-associating. 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-03-25 16:07 UTC, jaypipes requested changes
@RedbackThomson great work on this. You made the user experience of associating route tables to subnets entirely painless and aligned with the k8s resource model.

Couple teeny things to address inline but this is very close.

2022-03-25 16:07 UTC, jaypipes commented on pkg/resource/subnet/hooks.go
> +		rm.metrics.RecordAPICall("GET", "DescribeRouteTables", err)
this needs to go after the call to `rm.sdkapi.DescribeRouteTablesWithContext` otherwise the `err` won't be set properly and the metric for API errors will be wrong.

2022-03-25 16:07 UTC, jaypipes commented on test/e2e/tests/test_subnet.py
> +        ec2_validator.assert_subnet(resource_id, exists=False)
good work on these tests. ++

2022-03-25 16:07 UTC, jaypipes commented on test/e2e/tests/helper.py
> +        assert (self.get_route_table(route_table_id) is not None) == exists
this is not used. thankfully :)

2022-03-28 15:59 UTC, RedbackThomson commented on apis/v1alpha1/types.go
> +	Protocols         []*string `json:"protocols,omitempty"`
No clue why this showed up, honestly. I haven't touched the SDK version afaik

2022-03-29 15:47 UTC, brycahta requested changes
This is great and a really clean implementation. Appreciate the clear comments and cx (per jay's comment). Just had some small nits

2022-03-29 15:47 UTC, brycahta commented on pkg/resource/subnet/hooks.go
> +func (rm *resourceManager) getRouteTableAssocations(
typo: Associations

2022-03-29 15:47 UTC, brycahta commented on pkg/resource/subnet/hooks.go
> +			// our filter on the input has meant to have caught this.
nit: was meant to have caught this

2022-03-29 15:47 UTC, brycahta commented on pkg/resource/subnet/hooks.go
> +func toStrPtr(str string) *string {
surprised this isn't in `ackutils` or something similar

2022-03-29 15:47 UTC, brycahta commented on pkg/resource/subnet/hooks.go
> +func inAssocations(
typo: Associations

There are a few of the same throughout the PR I'll just let you grep vs. comment each instance

2022-03-29 17:29 UTC, RedbackThomson commented on pkg/resource/subnet/hooks.go
> +func toStrPtr(str string) *string {
Agree. I looked through runtime to find this, too. It's stupid that Go even needs something like this, but until they figure their stuff out we should probably do it for them.

2022-03-30 19:12 UTC, brycahta approved these changes

2022-03-30 20:08 UTC, brycahta reviewed
/lgtm

2022-03-30 20:08 UTC, merged