Generate `Reservation` CRD
aws-controllers-k8s/ec2-controller pull request #52
Opened 2022-04-27 21:22 UTC by brycahta

Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/1196

Description of changes:
* Allows the creation and termination of multiple instances by defining a `Reservation` resource backed by `RunInstances` , `DescribeInstances`, and `TerminateInstances` apis

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-04-27 21:36 UTC, brycahta commented
`kubectl describe reservations` sample output: https://gist.github.com/brycahta/66b1bea8c6f8810996344cc0bc0f0fee

This was a reservation for 2 instances and note the _Status_ section contains all instance details so kinda beefy.

2022-04-28 16:48 UTC, vijtrip2 approved these changes

2022-04-28 16:48 UTC, vijtrip2 commented on templates/hooks/reservation/sdk_delete_post_build_request.go.tpl
> +    if err = addInstanceIDsToTerminateRequest(r, input); err != nil {
Is it not possible to have zero instances in the reservation? Current code will error out of there are zero instances.

2022-04-28 17:04 UTC, brycahta commented on templates/hooks/reservation/sdk_delete_post_build_request.go.tpl
> +    if err = addInstanceIDsToTerminateRequest(r, input); err != nil {
> Is it not possible to have zero instances in the reservation?

Correct. From the [RunInstancesInput docs](https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#RunInstancesInput) for both `MinCount` and `MaxCount` fields: 

```
Constraints: Between 1 and the maximum number you're allowed for the specified
    // instance type.
```


I'm planning to have the next PR add exceptions/terminal_codes to communicate this properly

2022-04-29 15:44 UTC, vijtrip2 commented
/approve

2022-04-29 20:32 UTC, RedbackThomson requested changes
This is really great. I love that you went with `Reservation` as the CRD name - although SEO might be a bit tough for documentation, so hopefully we can figure that out. I have some initialisms for you, and some field paths to ignore, but nothing crazy.

2022-04-29 20:32 UTC, RedbackThomson commented on apis/v1alpha1/reservation.go
> +	ClientToken *string `json:"clientToken,omitempty"`
Please add to the ignore list

2022-04-29 20:32 UTC, RedbackThomson commented on apis/v1alpha1/reservation.go
> +	RamdiskID *string `json:"ramdiskID,omitempty"`
`RAM` should be added as a initialism

2022-04-29 20:32 UTC, RedbackThomson commented on apis/v1alpha1/types.go
> +	SriovNetSupport *string        `json:"sriovNetSupport,omitempty"`
`SRIOV` should be added as an initialism

2022-04-29 20:32 UTC, RedbackThomson commented on apis/v1alpha1/types.go
> +	ClientToken                      *string                                   `json:"clientToken,omitempty"`
Please add this to ignored

2022-05-03 19:09 UTC, RedbackThomson commented on apis/v1alpha1/reservation.go
> +	RAMdiskID *string `json:"ramdiskID,omitempty"`
What happened here? Why didn't it uppercase `Disk`?

2022-05-03 19:09 UTC, RedbackThomson commented on apis/v1alpha1/types.go
> +	ClientToken                      *string                                   `json:"clientToken,omitempty"`
This is coming from the Describe call, I believe. Please check

2022-05-03 19:15 UTC, brycahta commented on apis/v1alpha1/reservation.go
> +	RAMdiskID *string `json:"ramdiskID,omitempty"`
* RamdiskID --> RAMdiskID
* RamDiskID --> RAMDiskID

2022-05-03 19:16 UTC, brycahta commented on apis/v1alpha1/reservation.go
> +	RAMdiskID *string `json:"ramdiskID,omitempty"`
I overlooked the first format.. didn't see it in my grep. Will update rules & regen.

2022-05-03 19:57 UTC, RedbackThomson commented on apis/v1alpha1/reservation.go
> +	AdditionalInfo *string `json:"additionalInfo,omitempty"`
Ummm should this be ignored? It sounds like we can't use it anyway?

2022-05-03 20:13 UTC, brycahta commented
Discussed offline; renaming the resource to `Instance` and hard-coding min/max count to 1, so a single instance is created and can be managed/modified by the controller (i.e. able add volume to instance). If we proceed with `Reservation`, then there is no way to update the reservation/collection of instances in this way.

2022-05-23 15:18 UTC, brycahta commented
Stale; re-genning as `Instance` once https://github.com/aws-controllers-k8s/community/issues/1285 is resolved

2022-05-23 15:18 UTC, closed without merging