Generate `Instance` CRD
aws-controllers-k8s/ec2-controller pull request #55
Opened 2022-05-25 20:13 UTC by brycahta

Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/1196

Description of changes:
* Instance Controller create/delete functionality with smoke test

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-05-25 20:21 UTC, brycahta commented
I will be handling update/modify code as well as exceptions and TerminalConditions in the next PR. Until then, Instance is NOT able to achieve ResourceSynced state because of "rolling" late initialization for fields such as `BlockDeviceMappings`. 

**Detailed Details**
* If a user does not specify `BlockDeviceMappings` in the Spec, then neither the Create Response nor the subsequent Describe Response contains a populated `BlockDeviceMappings` field (good!)
* After multiple Describe calls (usually by the 3rd call here:  https://github.com/aws-controllers-k8s/runtime/blob/main/pkg/runtime/reconciler.go#L237 because LateInit is enabled), the `BlockDeviceMappings` field is eventually updated with a server-side value, ex:

```
//prev
BlockDeviceMappings: []

//updated
BlockDeviceMappings: [{
              DeviceName: "/dev/xvda",
              Ebs: {
                AttachTime: 2022-05-25 17:20:03 +0000 UTC,
                DeleteOnTermination: true,
                Status: "attaching",
                VolumeId: "vol-008cf94ebf53b06ec"
              }
            }],
```
* This triggers an update (not yet impl) and thus resource does not reach Sync state.
* Note, I have tried LateInitializing `BlockDeviceMappings`, but per the first point it does not apply here.

2022-05-25 20:32 UTC, RedbackThomson requested changes
I just want to make sure we're not duplicating fields between Spec and Status. I saw `VPCID` defined in Status, but I don't see it defined in Spec - which makes me wonder how I would set this value in the first place.

Also left a comment inline about testing methodology.

2022-05-25 20:32 UTC, RedbackThomson commented on apis/v1alpha1/instance.go
> +	MaxCount *int64 `json:"maxCount,omitempty"`
These should be removed from the spec?

2022-05-25 20:32 UTC, RedbackThomson commented on apis/v1alpha1/instance.go
> +	Tags []*Tag `json:"tags,omitempty"`
This is a duplicate of `TagSpecifications` essentially?

2022-05-25 20:32 UTC, RedbackThomson commented on test/e2e/tests/test_instance.py
> +    def test_create_delete(self, ec2_client):
Creating the resource, asserting, and deleting all within the test method itself inherently leaves it open to dangling resources. If an assertion fails, the delete methods will never be called, and the instances will be left running in the account. Please refer to the [EKS Cluster tests](https://github.com/aws-controllers-k8s/eks-controller/blob/main/test/e2e/tests/test_cluster.py#L57-L88) to see how I use fixtures to get around this. Essentially by creating and deleting within a fixture, the assertions can be made independently and not impact them.

2022-05-25 21:26 UTC, brycahta commented on test/e2e/tests/test_instance.py
> +    def test_create_delete(self, ec2_client):
Good call; addressing in next revision

2022-05-25 21:41 UTC, brycahta commented
>  I saw VPCID defined in Status, but I don't see it defined in Spec - which makes me wonder how I would set this value in the first place.

Good catch! By default, `RunInstances` API will use the **default VPC** and a random subnet. If you want to select which VPC+Subnet to use, then the *subnetID* needs to be specified in the request. Basically there's no way to pass a VPCID in the request. https://docs.aws.amazon.com/cli/latest/reference/ec2/run-instances.html

2022-05-26 16:45 UTC, brycahta commented on apis/v1alpha1/instance.go
> +	MaxCount *int64 `json:"maxCount,omitempty"`
After some deep dive, it looks like the code is **NOT** expected to remove these from Spec. These configs are at the operational level and don't seem to impact or be coupled with CRD Spec/Status in any way.  Another data point: the `override_values` in `rds-controller` are not present in the Spec because they never were. These fields apply to the operation only.

I know we have efforts to [move away from operation-centric configs](https://github.com/aws-controllers-k8s/community/issues/1185), which would be one way to address this. Or do you want me to open a new issue?

2022-05-27 20:08 UTC, RedbackThomson commented on apis/v1alpha1/instance.go
> +	Tags []*Tag `json:"tags,omitempty"`
> This should probably be reworked so Instance Controller can only tag Instance; I'm thinking remove TagSpecifications altogether and expose Tags in Spec. What do you think?

Yes! This should be the standard for all of the EC2 APIs, IMO

2022-06-01 14:20 UTC, brycahta commented on pkg/resource/instance/hooks.go
> +func updateTagSpecificationsInCreateRequest(r *resource,
@RedbackThomson this hook code is to support both `TagSpecifications` and `Tags` in the Spec, and I think this is necessary given the config limitations of _code-generator_. Open to other config suggestions if it's possible to support only Tags today; lmk.

**Detailed Details**
In an ideal world, I'd like to **ignore** `RunInstancesInput.TagSpecifications`; however, I need to reference this field in order to add `Tags` to the Spec. The add-to-Spec logic is coupled with *input shapes* and the only instance-related operation that had `Tags` shape in its input shape was `RunInstancesInput`

2022-06-01 14:21 UTC, brycahta commented on apis/v1alpha1/instance.go
> +	Tags []*Tag `json:"tags,omitempty"`
Agreed on this standard. 

However, not sure how straightforward or possible it is with existing _code-generator_ functionality. I left a comment with some more details, but tldr is I don't think I can ignore TagSpecifications and add Tags to Spec simultaneously. Might be worth investing in a better solution since this will apply to most EC2 APIs

2022-06-02 18:28 UTC, RedbackThomson approved these changes
Great job!

2022-06-02 18:28 UTC, RedbackThomson commented on pkg/resource/instance/hooks.go
> +		desiredTagSpecs.SetResourceType("instance")
nit: Move into a constant

2022-06-02 20:39 UTC, vijtrip2 approved these changes

2022-06-02 20:41 UTC, vijtrip2 commented
/lgtm

2022-06-02 20:42 UTC, merged