Internet Gateway terminal codes
aws-controllers-k8s/ec2-controller pull request #58
Opened 2022-07-12 21:55 UTC by LikithaVemulapalli

Issue #, if available: [1362](https://github.com/aws-controllers-k8s/community/issues/1362)

Description of changes:

Made the following changes in order to map exceptions for **internet gateway** resource in ec2-controller.
      - Added terminal codes in the "generator.yaml" for internet gateway resource.
      - Added few integration tests for internet gateway resource that cover invalid and malformed vpc-id.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-07-12 22:01 UTC, brycahta reviewed
/ok-to-test

2022-07-12 22:16 UTC, brycahta requested changes
Nice first PR! 🎉 

Had a couple comments on minor things, but overall very clean

2022-07-12 22:16 UTC, brycahta commented on generator.yaml
> +      - Resource.AlreadyAssociated
I don't think exceptions such as `Resource.AlreadyAssociated` and `Gateway.NotAttached` are possible given the [attach/detach implementation](https://github.com/aws-controllers-k8s/ec2-controller/blob/main/pkg/resource/internet_gateway/hook.go#L39). Am I missing context or can we remove?

2022-07-12 22:16 UTC, brycahta commented on test/e2e/tests/test_internet_gateway.py
> +        resource_name = random_suffix_name("ig-invalid-vpcid", 24)
`resource_name` is being assigned a `vpcid` value in both tests. Can you update so the name reflects the *internet gateway* resource?

2022-07-12 22:22 UTC, LikithaVemulapalli commented on generator.yaml
> +      - Resource.AlreadyAssociated
Yes I agree with the statement that these exceptions are not possible considering our implementation. We cannot test them, thought that we can include them in terminal codes, I can remove them!

2022-07-12 22:34 UTC, LikithaVemulapalli commented on test/e2e/tests/test_internet_gateway.py
> +        resource_name = random_suffix_name("ig-invalid-vpcid", 24)
I added resource_name values as per the failure scenarios, will update with the names that reflects the internet gateway resource.

2022-07-13 15:38 UTC, brycahta commented on generator.yaml
> +      - Resource.AlreadyAssociated
I'm thinking we just include the exceptions that are possible/testable:
```
      - InvalidVpcId.Malformed
      - InvalidVpcID.NotFound
```

@RedbackThomson @jaypipes  do y'all have other thoughts/opinions?

2022-07-13 16:16 UTC, vijtrip2 commented on generator.yaml
> +      - Resource.AlreadyAssociated
My 2 cents:

TL;DR: Vet carefully the exceptions being marked as terminal because missing an exception as terminal is better than marking a recoverable exception as terminal.

---
 
Terminal exceptions cause the reconciliation to stop. The exceptions added to the terminal exception should be vetted carefully. 
In case of some terminal exceptions not being added to this block, controller will just retry with exponential backoff. However if some recoverable exception gets added here, the reconciliation will cease.

---

Also NotFound errors should not be marked as terminal because we have seen customer submit their manifests out of order and some resources being created after their dependent resource.
In resource reference we handle this scenario, but have seen customer complaints in the past(they weren't using references)

2022-07-13 18:32 UTC, brycahta commented on generator.yaml
> +      - Resource.AlreadyAssociated
Appreciate the insights and feedback @vijtrip2 -- very helpful 👍 

All your points make sense to me. Basically, we only want `InvalidVpcId.Malformed` as a terminal exception for `InternetGateway` (Likitha & I have deep dived the other exceptions already) because reconciliation cannot "correct" this to a valid state. We can always add more exceptions to be terminal later should any issues arise. Feel free to correct anything/lmk if that sounds good. Thanks again

2022-07-14 14:12 UTC, brycahta reviewed
/lgtm

2022-07-14 14:13 UTC, merged