Adding Route table
aws-controllers-k8s/ec2-controller pull request #6
Opened 2021-09-03 16:54 UTC by brycahta

Issue #, if available: [#489](https://github.com/aws-controllers-k8s/community/issues/489)

Description of changes:
* adds route table resource
* refactors e2e tests to share common resources (i.e. VPC)
  * otherwise, vpcs would need to be created for each test which is inefficient and may exceed quota
  * now, only 2 vpcs are ever created per test run
  * could not use `@pytest.fixture(scope="session")` on vpc because we use [pytest-xdist](https://github.com/pytest-dev/pytest-xdist/issues/271)
* adds route table tests

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-09-03 16:54 UTC, brycahta commented
/cc @vijtrip2

2021-09-03 17:15 UTC, brycahta commented
/assign @RedbackThomson

2021-09-03 17:24 UTC, brycahta commented on test/e2e/conftest.py
> +# This implementation is needed to share resources with a "session" scope whether pytest-xdist is used or not.
will make this clearer in next revision. Any input would be appreciated!

2021-09-03 17:24 UTC, brycahta commented on test/e2e/conftest.py
> +    test_resource_values["VPC_ID"] = resource["status"]["vpcID"]
removing in next revision

2021-09-03 20:42 UTC, RedbackThomson reviewed
Seems pretty straightforward! No custom logic? Impressive.

Left some comments in your tests.

2021-09-03 20:42 UTC, RedbackThomson commented on test/e2e/conftest.py
> +# This implementation is needed to share resources with a "session" scope whether pytest-xdist is used or not.
I might actually recommend that you simply create the VPC in the `service_bootstrap`, instead. I understand that you would like to test your CRs using the VPC CR, but I think that would make all of the tests depend upon the correctness of your VPC implementation. There is a way to share session-scoped variables across pytest-xdist workers, but it's not fun.

2021-09-03 20:42 UTC, RedbackThomson commented on test/e2e/tests/test_route_table.py
> +            resp = ec2_client.describe_route_tables()
```suggestion
            resp = ec2_client.describe_route_tables(Filters=[{"Name": "route-table-id", "Values": [route_table_id]}]
```

This should filter by route table ID, and return only a single result - no need for iterating.

2021-09-03 20:42 UTC, RedbackThomson commented on test/e2e/tests/test_route_table.py
> +        except Exception as e:
Is this try/except necessary? Does `client.describe_route_tables()` throw an exception if there are none in the VPC? I imagine it would return an empty list, instead?

2021-09-03 20:42 UTC, RedbackThomson commented on test/e2e/tests/test_route_table.py
> +    def test_create_delete(self, ec2_client, pytestconfig):
Please see the (`sagemaker-controller` test code)[https://github.com/aws-controllers-k8s/sagemaker-controller/blob/main/test/e2e/tests/test_model.py#L34] for a better way to use fixtures. This code, currently, will not delete the custom resource if an assertion fails. It will assert and then immediately exit the method. Instead, we can use a fixture with a `yield`, which will continue even after the test fails.

2021-09-03 20:42 UTC, RedbackThomson commented on test/e2e/tests/test_subnet.py
> +    def test_create_delete(self, ec2_client, pytestconfig):
I know subnet was a previous PR, but please make the same changes as recommended above.

2021-09-07 13:54 UTC, jaypipes commented on test/e2e/tests/test_route_table.py
> +        except Exception as e:
@RedbackThomson is correct:

```
[jaypipes@thelio test-infra]$ aws ec2 describe-route-tables --filters Name=route-table-id,Values=non-existing --output json
{
    "RouteTables": []
}
```

2021-09-07 13:54 UTC, jaypipes commented on test/e2e/tests/test_route_table.py
> +    def get_route_table(self, ec2_client, route_table_id: str) -> dict:
You could more easily make these module-level functions since they don't depend on `self` or the instance/class

2021-09-07 13:54 UTC, jaypipes commented on test/e2e/tests/test_route_table.py
> +    def route_table_exists(self, ec2_client, route_table_id: str) -> bool:
module-level function

2021-09-07 13:54 UTC, jaypipes commented on test/e2e/tests/test_route_table.py
> +
nit: empty newline

2021-09-07 13:54 UTC, jaypipes commented on test/e2e/conftest.py
> +        k8s.delete_custom_resource(ref)
This is actually how I was envisioning a pytest-native plugin that would look for handling resource existence/cleanup. ++

2021-09-07 14:46 UTC, brycahta commented on test/e2e/conftest.py
> +# This implementation is needed to share resources with a "session" scope whether pytest-xdist is used or not.
> I think that would make all of the tests depend upon the correctness of your VPC implementation.

Right, that would be the intent (as well as other resources added to this cache eventually). If VPC implementation is not correct, then it should be caught during testing. And I also think it's best to test integrating these various pieces together during integration/e2e tests.

> There is a way to share session-scoped variables across pytest-xdist workers, but it's not fun.

Are you referring to writing data to a json file using a FileLock? I linked the latest open ticket related to this in the description above, and I'm fairly certain this implementation is simpler and just as safe.

2021-09-07 14:48 UTC, brycahta commented on test/e2e/tests/test_route_table.py
> +        except Exception as e:
Haven't tested yet-- but I'd guess it could throw an exception if credentials expire or aren't available, which is a possible scenario during _local_ testing on a kind cluster

2021-09-07 14:51 UTC, brycahta commented on test/e2e/tests/test_route_table.py
> +    def test_create_delete(self, ec2_client, pytestconfig):
Good point on the delete, I can deep dive that.

Our use-case for fixtures are not the same-- these are at the module scope not session. I was using vpc fixture in a similar way before these changes, but since more resources will also require vpc the module scope was too narrow

2021-09-07 14:58 UTC, brycahta commented on test/e2e/tests/test_route_table.py
> +        except Exception as e:
```
[7/09/21 9:57:50] ➜  ~ aws ec2 describe-route-tables --profile test-profile

An error occurred (AuthFailure) when calling the DescribeRouteTables operation: AWS was not able to validate the provided access credentials
```

2021-09-07 18:15 UTC, brycahta commented on test/e2e/tests/test_route_table.py
> +        except Exception as e:
Will refine exceptions in next revision

2021-09-07 21:15 UTC, brycahta commented on test/e2e/tests/test_route_table.py
> +        except Exception as e:
In this revision, the exception will also trigger if response has no resources as this is unexpected so I left exception as-is. Let me know if changes are needed/preferred.

2021-09-08 09:21 UTC, A-Hilaly approved these changes
Neat :+1:

2021-09-08 12:55 UTC, jaypipes requested changes

2021-09-08 12:55 UTC, jaypipes commented on test/e2e/tests/test_route_table.py
> +        logging.debug(e)
FYI, this won't log anything particularly useful in the case when the route table does not exist. Instead, you'll get something like `IndexError: 0 out of bounds` because of this line:

```python
route_table = resp["RouteTables"][0]
```

You might want to change that to this:

```python
if len(resp["RouteTables"]) == 0:
     return None
return resp["RouteTables"][0]
```

then your `except` clause will catch valid errors.

2021-09-08 12:55 UTC, jaypipes commented on test/e2e/tests/test_route_table.py
> +    return route_table if route_table["RouteTableId"] == route_table_id else None
this isn't necessary when using the filters above.

2021-09-08 12:55 UTC, jaypipes commented on test/e2e/tests/test_subnet.py
> +        subnet = resp["Subnets"][0]
similar comments as above about the IndexError

2021-09-08 12:55 UTC, jaypipes commented on test/e2e/tests/test_subnet.py
> +    return subnet if subnet["SubnetId"] == subnet_id else None
not necessary with the use of filters above.

2021-09-08 13:08 UTC, brycahta commented on test/e2e/tests/test_route_table.py
> +    return route_table if route_table["RouteTableId"] == route_table_id else None
-_-

2021-09-08 13:28 UTC, brycahta commented on test/e2e/tests/test_route_table.py
> +        logging.debug(e)
I feel like in this scenario it's "Easier to ask for forgiveness than permission" ([EAFP](https://docs.python.org/3.6/glossary.html#term-eafp)) because:
* we'd usually expect a single result when providing an ID
* we get savings on not needing to do the if check every time, but can still gate the no results scenario
* code is cleaner with less branched logic

The _0 out of bounds_ is not super helpful, but still an extra log to have when debugging tests. In both implementations the lack of a RouteTable would surface a failed `assert` that the resource doesn't exist so I don't think anything is lost there.

I don't think EAFP is more "pythonic" or better than "Look before you leap" ([LBYL](https://docs.python.org/3.6/glossary.html#term-lbyl)), but in this case I think it results in cleaner and clearer code.

Let me know your thoughts and I can update in next revision

2021-09-08 13:43 UTC, jaypipes commented on test/e2e/tests/test_route_table.py
> +        logging.debug(e)
> The _0 out of bounds_ is not super helpful, but still an extra log to have when debugging tests. In both implementations the lack of a RouteTable would surface a failed `assert` that the resource doesn't exist so I don't think anything is lost there.

What I'm saying is that "the resource doesn't exist" is not an error and should not log anything.

2021-09-08 15:07 UTC, jaypipes approved these changes
:tada:

2021-09-08 15:07 UTC, jaypipes commented
/lgtm

2021-09-08 15:08 UTC, merged