Add Rules to Security Group
aws-controllers-k8s/ec2-controller pull request #65
Opened 2022-08-01 21:35 UTC by brycahta

Issue #, if available: https://github.com/aws-controllers-k8s/community/issues/1326

Description of changes:
* Adds rules to SecurityGroup Spec and Status with tests

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-08-01 21:36 UTC, brycahta commented
> kubectl describe securitygroups

```
Name:         securitygroup-ack-test
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  ec2.services.k8s.aws/v1alpha1
Kind:         SecurityGroup
Metadata:
  Creation Timestamp:  2022-07-27T16:09:51Z
  Finalizers:
    finalizers.ec2.services.k8s.aws/SecurityGroup
  Generation:  1
  Managed Fields:
    API Version:  ec2.services.k8s.aws/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:description:
        f:egressRules:
        f:ingressRules:
        f:name:
        f:vpcID:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2022-07-27T16:09:51Z
    API Version:  ec2.services.k8s.aws/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"finalizers.ec2.services.k8s.aws/SecurityGroup":
      f:spec:
        f:tags:
      f:status:
        .:
        f:ackResourceMetadata:
          .:
          f:ownerAccountID:
          f:region:
        f:conditions:
        f:id:
        f:rules:
    Manager:         main
    Operation:       Update
    Time:            2022-07-27T16:09:54Z
  Resource Version:  87996072
  Self Link:         /apis/ec2.services.k8s.aws/v1alpha1/namespaces/default/securitygroups/securitygroup-ack-test
  UID:               03cbb789-e1fa-4e59-930a-a53fb2556621
Spec:
  Description:  My security Group
  Egress Rules:
    From Port:    80
    Ip Protocol:  tcp
    Ip Ranges:
      Cidr IP:      172.31.0.0/16
      Description:  test EGRESS sg rules
    To Port:        80
  Ingress Rules:
    From Port:    80
    Ip Protocol:  tcp
    Ip Ranges:
      Cidr IP:      172.31.0.0/16
      Description:  test INGRESS sg rules
    To Port:        80
  Name:             MyFirstGroup
  Vpc ID:           vpc-0101f5ec94e71f602
Status:
  Ack Resource Metadata:
    Owner Account ID:  515336597380
    Region:            us-west-2
  Conditions:
    Last Transition Time:  2022-07-27T16:09:54Z
    Message:               Resource synced successfully
    Reason:
    Status:                True
    Type:                  ACK.ResourceSynced
  Id:                      sg-0c8c63bd3f66af8f5
  Rules:
    cidrIPv4:                172.31.0.0/16
    Description:             test EGRESS sg rules
    From Port:               80
    Ip Protocol:             tcp
    Is Egress:               true
    Security Group Rule ID:  sgr-0715febb47a689187
    To Port:                 80
    cidrIPv4:                172.31.0.0/16
    Description:             test INGRESS sg rules
    From Port:               80
    Ip Protocol:             tcp
    Is Egress:               false
    Security Group Rule ID:  sgr-0c155c0eeebba694a
    To Port:                 80
Events:                      <none>
```

2022-08-01 21:51 UTC, RedbackThomson requested changes
Lots of custom code, but all looks great. Left some comments inline

2022-08-01 21:51 UTC, RedbackThomson commented on apis/v1alpha1/generator.yaml
> +          list_of: IpPermission
Hmmm. So on the console these are referred to as "Inbound" and "Outbound" rules. But in the CloudFormation and CDK resources these are called "Ingress" and "Egress". +1 for "Ingress/Egress"

2022-08-01 21:51 UTC, RedbackThomson commented on pkg/resource/security_group/hook.go
> +	ko.Spec.EgressRules = nil
Why are you nil-ing them out, here?

2022-08-01 21:51 UTC, RedbackThomson commented on templates/hooks/security_group/sdk_create_post_set_output.go.tpl
> +	}
I think I disagree with removing the default egress rule. If a user does not explicitly specify the rules, we should stick to the server-side default. (I believe) The vast majority of security groups will have the default egress rule, and so this is an expected behaviour by users. That being said, if they specify any egress rules, then we should override and delete the default.

2022-08-01 21:51 UTC, RedbackThomson commented on pkg/resource/security_group/hook.go
> +	ko.Status.Rules = nil
nit: Not necessary, since we override on line 86

2022-08-01 21:51 UTC, RedbackThomson commented on pkg/resource/security_group/hook.go
> +	}
My logic is that we should delete before we create for two reasons:
1. Updating a rule requires that it be removed before the updated version be added
2. If there is an error with adding new rules, it fails after it has already deleted the old ones. This is safer, since you have disabled the older rules.

2022-08-01 21:51 UTC, RedbackThomson commented on test/e2e/tests/test_security_group.py
> +        test_resource_values["DESCRIPTION_EGRESS"] = "test egress rule"
If these are hard-coded, then please just hardcode them in the YAML file

2022-08-01 21:51 UTC, RedbackThomson commented on test/e2e/tests/test_security_group.py
> +        print(f'{ref}')
nit: Remove print statements (they aren't shown in test logs anyway)

2022-08-01 21:57 UTC, brycahta commented on pkg/resource/security_group/hook.go
> +	ko.Spec.EgressRules = nil
Hmm not sure. I think it was leftover from testing; let me try to remove

2022-08-02 14:47 UTC, brycahta commented on test/e2e/tests/test_security_group.py
> +        test_resource_values["DESCRIPTION_EGRESS"] = "test egress rule"
Would you mind if I kept the assignments? I think it's clearer to see what is being created within the test and it doesn't require knowledge about how the tests work.

2022-08-02 14:56 UTC, brycahta commented on pkg/resource/security_group/hook.go
> +	}
Well said and makes sense to me! Going to add a comment with the same

2022-08-07 22:47 UTC, jaypipes commented on pkg/resource/security_group/hook.go
> +	ko.Spec.EgressRules = nil
@brycahta what if there are existing non-nil values for `ko.Spec.IngressRules` and `ko.Spec.EgressRules`? Do we want to nil those out even if `resp.IpPermissions` or `resp.IpPermissionsEgress` are nil?

2022-08-07 22:47 UTC, jaypipes commented on pkg/resource/security_group/hook.go
> +func (rm *resourceManager) addRulesToSpec(
would be great to have docstrings for these methods... :)

2022-08-07 22:47 UTC, jaypipes commented on pkg/resource/security_group/hook.go
> +	ko.Status.Rules = nil
we would not set `ko.Status.Rules` to nil if there was an error on line 83, though. And I think it's more appropriate to leave `ko.Status.Rules` as-is in the case of an error in `DescribeSecurityGroupRules`, no?

2022-08-07 22:47 UTC, jaypipes commented on pkg/resource/security_group/hook.go
> +// contains returns true if security group rule
perhaps `containsRule` might be a bit more descriptive of this function's purpose?

2022-08-07 22:47 UTC, jaypipes commented on templates/hooks/security_group/sdk_create_post_set_output.go.tpl
> +	}
Agree with @RedbackThomson here.

2022-08-07 22:47 UTC, jaypipes commented on pkg/resource/security_group/hook.go
> +}
unused AFAICT?

2022-08-07 22:47 UTC, jaypipes commented on test/e2e/tests/test_security_group.py
> +        print(f'{ref}')
@brycahta did you want to remove these?

2022-08-08 15:21 UTC, brycahta commented on test/e2e/tests/test_security_group.py
> +        print(f'{ref}')
Yes, I was "resolving" as I fixed things locally. Will be removed in next revision

2022-08-08 15:26 UTC, brycahta commented on pkg/resource/security_group/hook.go
> +	ko.Spec.EgressRules = nil
I don't think we want to nil those out; I removed setting to nil in both `addRulesToStatus` and `addRulesToSpec`.

2022-08-09 18:01 UTC, jaypipes reviewed
This is looking very good, @brycahta thank you! I left just one question inline for you. Depending on answer for that, I'd be ready to merge this.

2022-08-09 18:27 UTC, brycahta commented on pkg/resource/security_group/delta.go
> +	}
Thanks for the callout. I did some local testing:
* rearranging the order of `egressRules` and `ingressRules` did not trigger a delta difference
* rearranging the order of the rules within `ingressRules` did trigger a delta difference

2022-08-09 18:42 UTC, brycahta commented
> This is looking very good, @brycahta thank you! I left just one question inline for you. Depending on answer for that, I'd be ready to merge this.

@jaypipes Found a couple issues while testing locally hence the `do-not-merge` label. It's making me think `LateInitialize` is not the correct approach for `EgressRules`. Working on the fixes now; can discuss details on Slack once the outage is over, if you're interested.

2022-08-11 14:19 UTC, brycahta commented on pkg/resource/security_group/delta.go
> +	}
Discussed offline; neither scenario should trigger a delta difference because there is no change in **data**. Will create issue to add hook for `delta preCompare` (or similar) to sort prior to checking for equality. This needs to be done for any/all resources with list of struct fields

2022-08-11 14:22 UTC, brycahta commented on pkg/resource/security_group/hook.go
> +	ko.Spec.EgressRules = nil
I was wrong for `addRulesToSpec`. This is needed because `sdkUpdate` will make a call to `sdkFind` to get the latest resource state which then executes this code. If the latest resource state DOES NOT contain rules, then the rules from the previous resource state will persist as they are never nil-ed out.

2022-08-11 14:48 UTC, jaypipes reviewed
@brycahta one final question inline...

2022-08-11 14:48 UTC, jaypipes commented on pkg/resource/security_group/hook.go
> +		}
Is this additional call to `sdkFind()` necessary? Won't `latest` already have the latest `Spec` information?

2022-08-11 14:54 UTC, brycahta commented on pkg/resource/security_group/hook.go
> +		}
Yes, it's necessary. For example, `latest` may contain an egress rule while `desired` does not. After call to `syncSGRules`, that egress rule should be removed server-side but the `latest` Spec will still contain it. The call to `sdkFind()` then refreshes both Spec/Status rules with latest data from server, resulting in `latest` having its Spec and Status updated to no longer include the deleted rule.

2022-08-11 14:56 UTC, jaypipes commented on pkg/resource/security_group/hook.go
> +		}
Why not just return `desired` here then?

2022-08-11 15:02 UTC, brycahta commented on pkg/resource/security_group/hook.go
> +		}
If I returned desired, then I don't think the `Status.Rules` will be an accurate representation of the rules existing server-side. That data isn't available until after `syncSGRules()` call and then `sdkFind()` updates both Spec+Status with the latest data.

2022-08-11 15:47 UTC, jaypipes commented on pkg/resource/security_group/hook.go
> +		}
Hmm, I see... instead of calling the full `sdkFind` method, then, what about just setting `Status.Rules` at the end of `syncSGRules` by calling `DescribeSecurityGroupRules` then?

2022-08-11 17:40 UTC, brycahta commented on pkg/resource/security_group/hook.go
> +		}
I need the full `sdkFind` method (i.e. update both Spec and Status) on `Update` because of the scenario when user updates SecurityGroup with their own EgressRule. 

The intended behavior is remove default egress rule if user provides one and since this is done automatically, the `desired` Spec will still include the default egress rule if we only update `Status.Rules` in `Update`

2022-08-12 20:50 UTC, jaypipes approved these changes
This is great, @brycahta thank you! I would love to see a tutorial (or addition to the github.com/aws-controllers-k8s/examples` repository) that shows how to use this new functionality, since it's functionality that isn't covered directly by the ACK resource reference.

2022-08-12 20:50 UTC, jaypipes commented
/lgtm

2022-08-12 20:51 UTC, merged