Update tags support for Subnet
aws-controllers-k8s/ec2-controller pull request #81
Opened 2022-08-26 17:03 UTC by LikithaVemulapalli

Description of changes:

-  Added custom code that supports updating tags for **Subnet** resource.
- Added integration test to check whether tags are being updated as expected.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-08-26 17:32 UTC, A-Hilaly commented
/ok-to-test

2022-08-26 17:44 UTC, LikithaVemulapalli commented
/retest

2022-08-29 17:00 UTC, LikithaVemulapalli commented
/retest

2022-08-29 17:05 UTC, LikithaVemulapalli commented
/retest

2022-08-29 18:38 UTC, LikithaVemulapalli commented
/retest

2022-08-29 18:45 UTC, LikithaVemulapalli commented
/retest

2022-08-30 15:07 UTC, brycahta requested changes
Nice work @LikithaVemulapalli ! Very excited to get this tagging functionality in.

2022-08-30 15:07 UTC, brycahta commented on test/e2e/tests/test_subnet.py
> +        test_resource_values["KEY"] = "createKey"
related to comment above; I'm assuming if you don't define these then the tests will fail? If so, can you add an assert check on this tag? If we define the data, then we should validate it

2022-08-30 15:07 UTC, brycahta commented on test/e2e/tests/test_subnet.py
> +    def test_update_tags(self, ec2_client):
Update tags test looks solid 👍  

Would you consider expanding the test coverage on tags a bit and updating this to a `test_crud_tags`? After your update check:
1.  **add** a 2nd tag to the resource --> validate data
2. **delete** a tag from the resource --> validate data

This will exercise the paths of adding a tag post-creation and also deleting a tag while resource is active

2022-08-30 15:15 UTC, LikithaVemulapalli commented on pkg/resource/subnet/hooks.go
> +func compareTags(
I haven't tried using go templates, but I like this idea as the code will be consistent with the other compare functions, will make changes accordingly. Thank you!

2022-08-30 15:44 UTC, LikithaVemulapalli commented on test/e2e/tests/test_subnet.py
> +        test_resource_values["KEY"] = "createKey"
As mentioned earlier, tests won't fail if tags are not defined, I added here so that they align with the resource file. But I can delete tags from `test_create_delete` as I'm planning to add tests for checking tags creation and deletion as per below comment.

2022-09-06 20:58 UTC, LikithaVemulapalli commented on pkg/resource/subnet/hooks.go
> +// equalTags function used to compare whether two tag arrays are equal or not
Removed `equalTags` function, not required when using go templates.

2022-09-06 21:37 UTC, brycahta requested changes
Can you regenerate without local changes in _code-generator_ to maintain `v0.19.3`? Otherwise, looks great!

2022-09-06 21:51 UTC, RedbackThomson commented on templates/hooks/subnet/sdk_file_end.go.tpl
> +{{- end }}
Ew. I hate that we have to do this. Not blaming you at all for this ugly mess, it totally makes sense. My s3 controller hacks unfortunately have set a precedent for relying too heavily on generated `sdk_file_end` hooks. @A-Hilaly I think we should expedite our generic tagging support to prevent ... this

2022-09-06 22:59 UTC, A-Hilaly commented on templates/hooks/subnet/sdk_file_end.go.tpl
> +{{- end }}
+1 for what Nick said here. @RedbackThomson Indeed, i will open an issue to track and discuss how we can achieve the generic tagging support.

2022-09-07 13:47 UTC, brycahta commented on templates/hooks/subnet/sdk_file_end.go.tpl
> +{{- end }}
Sounds good; lmk once you have the issue so we can gauge the effort. Might need to rely on copy/paste this template style for other resources if dev effort is more than a couple weeks

2022-09-07 13:53 UTC, brycahta approved these changes
/lgtm

2022-09-07 13:58 UTC, merged