UpdateTags support for VPC
aws-controllers-k8s/ec2-controller pull request #90
Opened 2022-09-07 23:46 UTC by LikithaVemulapalli

Issue #, if available:

Description of changes:

- Implemented updateTags support for **VPC** resource using go templates and hook code.
- Added integration tests for updateTags.
- Removed existing `delta_pre_compare.go.tpl` file from subnet templates as we are using `sdk_file_end.go.tpl`.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-09-08 15:35 UTC, jaypipes commented on test/e2e/conftest.py
> +            replacements["VALUE"] = data['value']
recommend naming these variables `TAG_KEY` and `TAG_VALUE` to save the reader some trouble in the future wondering what they refer to :)

2022-09-08 15:35 UTC, jaypipes commented on templates/hooks/vpc/sdk_file_end.go.tpl
> +func compare{{ $vpcRefName }}(
Where are any of these `compareXXX` functions being called?

2022-09-08 17:50 UTC, LikithaVemulapalli commented on templates/hooks/vpc/sdk_file_end.go.tpl
> +func compare{{ $vpcRefName }}(
My bad! Initially I did implement using compareTags function, but later after suggestions in previous subnet PR, converted logic to use go templates, thought I would need `compareTag` at some point later and included it, cross-checked with local testing, no need for this `compareTag` function anymore, thank you for noticing it! Will remove this function for `subnet` resource as well!

2022-09-08 19:35 UTC, brycahta commented on test/e2e/conftest.py
> +        if 'key' in data:
nit: could you update this to also be `tag_key` / `tag_value`?

2022-09-08 19:36 UTC, brycahta approved these changes
Thanks @LikithaVemulapalli ; looks good! Will let @jaypipes re-review before merging

2022-09-08 21:26 UTC, A-Hilaly approved these changes
:+1:

2022-09-08 22:53 UTC, jaypipes commented on pkg/resource/vpc/hook.go
> +	for _, i := range tags {
Is there a reason we need to make multiple calls to `DeleteTags` instead of just calling it once with the `DeleteTagsInput.Tags` field set to all the tags we want to delete?

2022-09-08 22:53 UTC, jaypipes commented on pkg/resource/vpc/hook.go
> +	for _, i := range tags {
Is there a reason we need to make multiple calls to `CreateTags` instead of just calling it once with the `CreateTagsInput.Tags` field set to all the tags we want to create?

2022-09-09 15:54 UTC, LikithaVemulapalli commented on pkg/resource/vpc/hook.go
> +	for _, i := range tags {
Initially I thought it would be clear to have separate functions for creation and deletion of tags. To align with the other svcapitypes to svcsdk tag conversions in EC2 controller, I need to use the go templates. The `newTag` function converts only single tag at a time (cross-checked with the target shape) , so thought about the iterations. But, this can be done in other way as well, like instead of making multiple calls to API's, we can add a function to convert to sdktags and call it in `DeleteTagsInput.Tags`, will change accordingly, if you feel this would be more ideal! Thank you!

2022-09-09 15:55 UTC, LikithaVemulapalli commented on pkg/resource/vpc/hook.go
> +	for _, i := range tags {
Same explanation as above! Will change it accordingly if needed!

2022-09-12 14:49 UTC, jaypipes requested changes

2022-09-12 14:49 UTC, jaypipes commented on pkg/resource/vpc/hook.go
> +	for _, i := range tags {
Sorry @LikithaVemulapalli I'm not explaining myself correctly. I meant would it be possible to reduce the number of API calls made here (and below in the delete code paths) by doing this?

```go
func (rm *resourceManager) createTags(
	ctx context.Context,
	r *resource,
	tags []*svcapitypes.Tag,
) (err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.createTags")
	defer exit(err)

	resourceId := []*string{r.ko.Status.VPCID}

	sdkTags := make([]*svcsdk.Tag, len(tags))
	for x, tag := range tags {
		toAdd := rm.newTag(*tag)
		sdkTags[x] = toAdd
	}
	req := &svcsdk.CreateTagsInput{
		Resources: resourceId,
		Tags: sdkTags,
	}
	_, err := rm.sdkapi.CreateTagsWithContext(ctx, req)
	rm.metrics.RecordAPICall("CREATE", "CreateTags", err)
	return err
}
```

2022-09-12 15:41 UTC, LikithaVemulapalli commented on pkg/resource/vpc/hook.go
> +	for _, i := range tags {
Yes, it's possible to reduce number of API calls by calling a separate function to append all the converted sdk tags and passing it as input! Will change accordingly! Thank you!

2022-09-13 15:16 UTC, LikithaVemulapalli commented
/retest

2022-09-13 15:21 UTC, brycahta approved these changes
/lgtm

appreciate the improvements 👍

2022-09-13 15:22 UTC, merged

2022-09-13 20:16 UTC, jaypipes commented on pkg/resource/vpc/hook.go
> +		rlog.Debug("removing tags from parameter group", "tags", toDelete)
is this removing tags from parameter group? or VPC? :)

2022-09-13 20:16 UTC, jaypipes commented on pkg/resource/vpc/hook.go
> +		rlog.Debug("adding tags to parameter group", "tags", toAdd)
ditto :)

2022-09-13 20:41 UTC, brycahta commented on pkg/resource/vpc/hook.go
> +		rlog.Debug("removing tags from parameter group", "tags", toDelete)
fixed in follow-up PR: https://github.com/aws-controllers-k8s/ec2-controller/pull/92/files#diff-12b9f9c625e91af04b8e0bb655157fff51de25c8f72b891312a761b212d3e018R309

2022-09-13 20:47 UTC, LikithaVemulapalli commented on pkg/resource/vpc/hook.go
> +		rlog.Debug("adding tags to parameter group", "tags", toAdd)
Fixed in follow-up PR: https://github.com/aws-controllers-k8s/ec2-controller/pull/92/files#diff-12b9f9c625e91af04b8e0bb655157fff51de25c8f72b891312a761b212d3e018R309